language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
deploy:
  on:
    tags: true
  provider: npm
  email: "marvinshawn9333@gmail.com"
  api_key: "${NPM_TOKEN}"
  skip_cleanup: true