language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true